name: Update README Animations

on:
  schedule:
    - cron: "0 */6 * * *" # Atualiza a cada 6 horas
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake (Light and Dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: NathanDalbert
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar estatísticas do WakaTime no README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
