name: Waka Readme

on:
  schedule:
    # Roda a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "true"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "false"
          SHOW_LANGUAGE: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_LOC_CHART: "false"
          LANG_COUNT: "5"
